language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
    allow_failures:
        - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --prefer-dist --dev

script: ./vendor/bin/phpunit --configuration phpunit.xml
